
def get_case(num):
	if num == 0:
		print("  *****")
		print("  *  **")
		print("  U  **")
		print("  R  **")
		print(" DED **")
		print("     **")
	if num == 1:
		print("  *****")
		print("  *  **")
		print("  O  **")
		print("  i  **")
		print(" J L **")
		print("     **")
	if num == 2:
		print("  *****")
		print("  *  **")
		print("  O  **")
		print("  i  **")
		print(" J   **")
		print("     **")
	if num == 3:
		print("  *****")
		print("  *  **")
		print("  O  **")
		print("  i  **")
		print("     **")
		print("     **")
	if num == 4:
		print("  *****")
		print("  *  **")
		print("  O  **")
		print("     **")
		print("     **")
		print("     **")
	if num == 5:
		print("  *****")
		print("  *  **")
		print("     **")
		print("     **")
		print("     **")
		print("     **")
	if num == 6:
		print("  	  ")
		print("  	  ")
		print("       ")
		print("       ")
		print("       ")
		print("       ")